"""create sec filing tables

Revision ID: e0692c2ea6dc
Revises: 
Create Date: 2026-09-23 17:13:22.600205

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e0692c2ea6dc'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cik')
    )
    op.create_table('ingestion_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filings_discovered', sa.Integer(), nullable=False),
    sa.Column('filings_saved', sa.Integer(), nullable=False),
    sa.Column('sections_saved', sa.Integer(), nullable=False),
    sa.Column('facts_saved', sa.Integer(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_ingestion_runs_ticker'), 'ingestion_runs', ['ticker'], unique=False)
    op.create_table('company_tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'cik', name='uq_company_tickers_ticker_cik')
    )
    op.create_index(op.f('ix_company_tickers_cik'), 'company_tickers', ['cik'], unique=False)
    op.create_index(op.f('ix_company_tickers_ticker'), 'company_tickers', ['ticker'], unique=False)
    op.create_table('filings',
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('primary_document', sa.String(length=500), nullable=True),
    sa.Column('html_url', sa.Text(), nullable=False),
    sa.Column('archive_directory_url', sa.Text(), nullable=False),
    sa.Column('selection_reason', sa.String(length=32), nullable=False),
    sa.Column('is_amendment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('accession_number')
    )
    op.create_index(op.f('ix_filings_cik'), 'filings', ['cik'], unique=False)
    op.create_index(op.f('ix_filings_filing_date'), 'filings', ['filing_date'], unique=False)
    op.create_index(op.f('ix_filings_form_type'), 'filings', ['form_type'], unique=False)
    op.create_index(op.f('ix_filings_report_date'), 'filings', ['report_date'], unique=False)
    op.create_table('filing_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('item_code', sa.String(length=30), nullable=False),
    sa.Column('item_label', sa.String(length=500), nullable=False),
    sa.Column('content_raw', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('document_kind', sa.String(length=30), nullable=False),
    sa.Column('source_start', sa.Integer(), nullable=True),
    sa.Column('source_end', sa.Integer(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accession_number'], ['filings.accession_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', 'item_code', 'parser_version', name='uq_filing_sections_accession_item_parser')
    )
    op.create_index(op.f('ix_filing_sections_accession_number'), 'filing_sections', ['accession_number'], unique=False)
    op.create_index(op.f('ix_filing_sections_content_hash'), 'filing_sections', ['content_hash'], unique=False)
    op.create_index(op.f('ix_filing_sections_item_code'), 'filing_sections', ['item_code'], unique=False)
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_key', sa.String(length=64), nullable=False),
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('namespace', sa.String(length=100), nullable=True),
    sa.Column('concept', sa.String(length=200), nullable=True),
    sa.Column('value_numeric', sa.Numeric(precision=36, scale=10), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=10), nullable=True),
    sa.Column('form_type', sa.String(length=20), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('frame', sa.String(length=100), nullable=True),
    sa.Column('is_instant', sa.Boolean(), nullable=False),
    sa.Column('derived', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accession_number'], ['filings.accession_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', 'metric_key', 'unit', 'start_date', 'end_date', 'concept', name='uq_financial_facts_natural_key'),
    sa.UniqueConstraint('fact_key')
    )
    op.create_index(op.f('ix_financial_facts_accession_number'), 'financial_facts', ['accession_number'], unique=False)
    op.create_index(op.f('ix_financial_facts_end_date'), 'financial_facts', ['end_date'], unique=False)
    op.create_index(op.f('ix_financial_facts_fiscal_year'), 'financial_facts', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_financial_facts_metric_key'), 'financial_facts', ['metric_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_facts_metric_key'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_fiscal_year'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_end_date'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_accession_number'), table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_index(op.f('ix_filing_sections_item_code'), table_name='filing_sections')
    op.drop_index(op.f('ix_filing_sections_content_hash'), table_name='filing_sections')
    op.drop_index(op.f('ix_filing_sections_accession_number'), table_name='filing_sections')
    op.drop_table('filing_sections')
    op.drop_index(op.f('ix_filings_report_date'), table_name='filings')
    op.drop_index(op.f('ix_filings_form_type'), table_name='filings')
    op.drop_index(op.f('ix_filings_filing_date'), table_name='filings')
    op.drop_index(op.f('ix_filings_cik'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_company_tickers_ticker'), table_name='company_tickers')
    op.drop_index(op.f('ix_company_tickers_cik'), table_name='company_tickers')
    op.drop_table('company_tickers')
    op.drop_index(op.f('ix_ingestion_runs_ticker'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('companies')
    # ### end Alembic commands ###
